spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/listings/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
