spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/urban-radius
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

urban-radius:
  user-service-url: http://user-service
  catalog-service-url: http://catalog-service
  payment-service-url: http://payment-service
  kafka:
    booking-events-topic: booking-events
