spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5436/urban_radius_notifications
    username: urban
    password: urban
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
