spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/urban_radius_orders
    username: urban
    password: urban
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      auto-create: true

urban-radius:
  outbox:
    relay-interval-ms: 5000
